#!/bin/bash

website=""
subber=""
quality="$2" # Optional

# Check for quality, default is 720p
if [ -n $quality ]; then
    quality="\[${quality}\]"
else
    quality="\[720p\]"
fi

query="$(echo "$1" | sed 's/ /+/g')"

magnet="$(curl -s "${website}/user/${subber}?f=0&c=0_0&q=${query}+${quality}" | grep -m 1 "magnet" | sed -e 's/.*<a href="//' -e 's/">.*//' -e 's/\&amp;/\&/g')"

transmission-remote -a "$magnet"
